"""Export every engine dimension and fit to skin/params.json - the single source
of truth the Blender skin script reads. Nothing in tools/skin/ holds a number
that also lives in config.py / fits.py.

    python tools/export_params.py
"""

import json
import math
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
sys.path.insert(0, os.path.join(ROOT, "cad"))

import config as C  # noqa: E402
import fits  # noqa: E402
import block  # noqa: E402

OUT = os.path.join(ROOT, "skin", "params.json")


def _jsonable(v):
    if isinstance(v, (bool, int, float, str)) or v is None:
        return v
    if isinstance(v, (list, tuple)):
        return [_jsonable(x) for x in v]
    if isinstance(v, dict):
        return {str(k): _jsonable(x) for k, x in v.items()}
    return None


def build():
    cfg = {}
    for name in dir(C):
        if not name.isupper() or name.startswith("_"):
            continue
        v = _jsonable(getattr(C, name))
        if v is not None:
            cfg[name] = v
    fit = {name: _jsonable(getattr(fits, name)) for name in dir(fits)
           if name.isupper() and _jsonable(getattr(fits, name)) is not None}
    derived = {
        "variant": C.VARIANT,
        "bank_between_x": block.bank_between_x(),
        "block_end_screws_x": block.block_end_screws_x(),
        "locator_xy": block.locator_xy(),
        "case_end_screws": block.CASE_END_SCREWS,
        "end_plate_screws": block.END_PLATE_SCREWS,
        "base_inserts": block.BASE_INSERTS,
        "crankcase_outer_profile_yz": block.outer_profile(),
        "beam_profile_yz": block.beam_profile(),
        "bank_angle_A": C.bank_angle("A"), "bank_angle_B": C.bank_angle("B"),
        "cyl_bank": {c: C.cyl_bank(c) for c in range(1, C.N_CYL + 1)},
        "cyl_throw": {c: C.cyl_throw(c) for c in range(1, C.N_CYL + 1)},
        "fire_angle": {c: C.FIRE_ANGLE[c] for c in range(1, C.N_CYL + 1)},
        "hole": {k: C.hole(d) for k, d in (("M3_CLEAR", C.M3_CLEAR), ("M3_CBORE", C.M3_CBORE))},
        "insert_hole": C.hole(C.INSERT_HOLE_DIA - C.HOLE_COMP, "insert_m3"),
        "crush": {k: dict(zip(("n_ribs", "bore", "rib_r", "rib_centre_r"), [_jsonable(x) for x in __import__("common").crush_params(d, k)]))
                  for k, d in (("magnet_6", C.MAGNET["d"]), ("trumpet_14", C.EXH_SPIGOT_D), ("boot_9", C.PLUG_BOOT["shaft_d"]),
                               ("bearing_608", C.BEARING_608["od"]), ("bearing_686", C.BEARING_686["od"]), ("rail_3", C.RAIL_DIA))},
    }
    # dpin_shaft uses the D-pin fit table entry with the crank shaft diameter (as cad/common.crush_d_x)
    derived["crush"]["dpin_shaft"] = dict(zip(("n_ribs", "bore", "rib_r", "rib_centre_r"),
                                              [_jsonable(x) for x in __import__("common").crush_params(C.SHAFT_D, "dpin_6")]))
    if C.VARIANT == "v8":
        import pan_v8, stand_v8
        derived.update({
            "edition_y": stand_v8.EDITION_Y,
            "board_stack": pan_v8.BOARD_STACK,
            "pan_panel_screws": pan_v8.panel_screws(),
            "pan_board_holes": pan_v8._board_holes(),
            "pan_board_centre": list(pan_v8._board_centre()),
            "pan_rabbet": [pan_v8.RX0, pan_v8.RX1, pan_v8.RY0, pan_v8.RY1],
            "pan_opening": [pan_v8.PX0, pan_v8.PX1, pan_v8.PY0, pan_v8.PY1],
            "pan_interior": [pan_v8.IX0, pan_v8.IX1, pan_v8.IY0, pan_v8.IY1],
            "edition_texts": [["358 ci  V8  -  90 DEG  CROSS-PLANE", 5.0, 5.5],
                              ["-".join(str(c) for c in C.FIRING_ORDER) + "      No. {number:02d} / 50", 3.6, -6.0]],
            "plinth_labels": {"dc_jack": "12V DC", "power": "POWER", "speed": "SPEED", "start": "START"},
        })
    return {"source": "generated by tools/export_params.py from config.py (variant %s) and fits.py - do not edit" % C.VARIANT,
            "config": cfg, "fits": fit, "derived": derived}


if __name__ == "__main__":
    data = build()
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        json.dump(data, f, indent=1, sort_keys=True)
    print("wrote", OUT, f"({len(data['config'])} config values, {len(data['fits'])} fit values, {len(data['derived'])} derived)")
