"""Generate firmware/v10_engine/engine_geometry.h from config.py.

The firmware never hard-codes engine geometry: the firing angles, the LED
layout on the two strips and the step counts all come from the same
config.py the CAD is built from.

    python tools/gen_firmware_config.py
"""

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
import config as C  # noqa: E402

OUT = os.path.join(ROOT, "firmware", "v10_engine", "engine_geometry.h")


def build():
    steps_rev = C.MOTOR_FULL_STEPS * C.MICROSTEPS * C.DRIVE_RATIO
    assert abs(steps_rev - round(steps_rev)) < 1e-9, "steps per crank revolution must be an integer"
    steps_rev = int(round(steps_rev))
    steps_cycle = 2 * steps_rev                       # 4-stroke cycle = 720 crank degrees
    per_deg = steps_cycle / 720.0

    fire_step = []
    for c in range(1, C.N_CYL + 1):
        s = C.FIRE_ANGLE[c] * per_deg
        assert abs(s - round(s)) < 1e-6, f"cylinder {c}: firing angle is not a whole number of steps"
        fire_step.append(int(round(s)) % steps_cycle)

    # LED strips: one per bank, data enters at the REAR end of each head.
    # Strip LED k sits at k LED pitches from the rear-most LED; three LEDs per bore.
    n = C.LED_STRIP["n"]
    per_cyl = round(C.CYL_PITCH / C.LED_STRIP["pitch"])
    assert abs(per_cyl * C.LED_STRIP["pitch"] - C.CYL_PITCH) < 0.05, "cylinder pitch must be a whole number of LEDs"
    assert n == per_cyl * C.N_THROWS, "strip length must cover every bore"
    strips = {}
    for bank in ("A", "B"):
        cyls = [c for c in range(1, C.N_CYL + 1) if C.cyl_bank(c) == bank]
        cyls.sort(key=lambda c: -C.cyl_throw(c))          # rear-most first (throw 5 at the rear)
        strips[bank] = [(cyls[k // per_cyl], k % per_cyl) for k in range(n)]

    lines = [
        "// GENERATED by tools/gen_firmware_config.py from config.py - do not edit.",
        "// Change config.py and re-run the generator instead.",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "namespace geo {",
        f"constexpr uint32_t MOTOR_FULL_STEPS = {C.MOTOR_FULL_STEPS};",
        f"constexpr uint32_t MICROSTEPS = {C.MICROSTEPS};",
        f"constexpr uint32_t DRIVE_RATIO = {int(C.DRIVE_RATIO)};              // {C.PULLEY_BIG['teeth']}T / {C.PULLEY_SMALL['teeth']}T GT2",
        f"constexpr uint32_t STEPS_PER_REV = {steps_rev};          // motor microsteps per crank revolution",
        f"constexpr uint32_t STEPS_PER_CYCLE = {steps_cycle};       // one 720 deg 4-stroke cycle",
        f"constexpr int N_CYL = {C.N_CYL};",
        f"constexpr int FIRING_ORDER[N_CYL] = {{{', '.join(str(c) for c in C.FIRING_ORDER)}}};",
        "// step (within the 720 deg cycle, counted from cylinder 1 firing TDC) at which",
        "// each cylinder fires; index 0 = cylinder 1",
        f"constexpr uint32_t FIRE_STEP[N_CYL] = {{{', '.join(str(s) for s in fire_step)}}};",
        "",
        f"constexpr int LEDS_PER_STRIP = {n};",
        f"constexpr int LEDS_PER_CYL = {per_cyl};",
        "// strip LED k (k = 0 at the rear, data-in end): cylinder number and position",
        "// in its group (0 = rear LED, 1 = centre of the bore, 2 = front LED)",
    ]
    for bank in ("A", "B"):
        cy = ", ".join(str(c) for c, _ in strips[bank])
        po = ", ".join(str(p) for _, p in strips[bank])
        lines.append(f"constexpr uint8_t LED_CYL_{bank}[LEDS_PER_STRIP] = {{{cy}}};")
        lines.append(f"constexpr uint8_t LED_POS_{bank}[LEDS_PER_STRIP] = {{{po}}};")
    lines += [
        "",
        f"constexpr float RPM_MIN = {C.ENGINE_RPM[0]:.1f}f;",
        f"constexpr float RPM_MAX = {C.ENGINE_RPM[1]:.1f}f;",
        f"constexpr float RPM_IDLE = {C.IDLE_RPM:.1f}f;",
        f"constexpr float RPM_HOMING = {C.HOMING_RPM:.1f}f;",
        f"constexpr float ACCEL_RPM_S = {C.CRANK_ACCEL_RPM_S:.1f}f;",
        f"constexpr uint32_t AUTO_IDLE_MIN = {C.AUTO_IDLE_MIN};",
        f"constexpr uint32_t AUTO_SLEEP_MIN = {C.AUTO_SLEEP_MIN};",
        f"constexpr uint16_t MOTOR_RUN_MA = {C.MOTOR_RUN_MA};",
        f"constexpr float MOTOR_HOLD_FRACTION = {C.MOTOR_HOLD_FRACTION:.2f}f;",
        f"constexpr uint32_t HALL_MIN_WIDTH = {int(C.HALL_PULSE_DEG[0] * per_deg)};      // steps",
        f"constexpr uint32_t HALL_MAX_WIDTH = {int(C.HALL_PULSE_DEG[1] * per_deg)};",
        f"constexpr int32_t SYNC_CORRECT_STEPS = {int(C.SYNC_CORRECT_DEG * per_deg)};",
        f"constexpr int32_t SYNC_FAULT_STEPS = {int(C.SYNC_FAULT_DEG * per_deg)};",
        f"constexpr uint32_t NO_HALL_STEPS = {int(C.NO_HALL_REVS * steps_rev)};",
        f"constexpr uint32_t FLASH_STEPS = {int(C.FLASH_DEG * per_deg)};",
        f"constexpr uint8_t LED_MAX_BRIGHTNESS = {C.LED_MAX_BRIGHTNESS};",
        "}  // namespace geo",
        "",
    ]
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    return OUT


if __name__ == "__main__":
    print("wrote", build())
