"""50-unit print plan and production timeline -> docs/PRODUCTION_PLAN.md

Uses the sliced times and grams from tools/printcheck.py (docs/print_results.json)
and packs the parts of a batch of engines onto build plates (one layer height
per plate), so the farm can be sized and scheduled.

    python tools/production_plan.py
"""

import json
import math
import os
import sys

import trimesh

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
sys.path.insert(0, os.path.join(ROOT, "cad"))
sys.path.insert(0, os.path.join(ROOT, "tools"))

import config as C  # noqa: E402

BED = (340.0, 320.0)       # Bambu Lab H2D / H2S class (the 300 mm parts need it)
GAP = 8.0                  # spacing between parts on a plate
UNITS = 50
BATCH = 5                  # engines per print batch (small parts are pooled across a batch)
UTILISATION = 0.85         # plate changes, preheat, maintenance
REPRINT = 1.05             # +5 % failed / rejected prints
FARM_SIZES = (4, 6, 8, 10, 12)
LABOUR_H = dict(prep=0.75, board=1.0, harness=0.35, assembly=1.85, burnin_handling=0.5, qc_pack=0.5)


def footprint(name):
    m = trimesh.load(os.path.join(ROOT, "stl", name + ".stl"), force="mesh")
    ext = m.bounds[1] - m.bounds[0]
    return float(ext[0]), float(ext[1])


def pack(items):
    """Shelf packing of (name, w, d, hours, grams) rectangles; parts may turn 90 deg.
    Returns a list of plates, each a list of items."""
    items = sorted(items, key=lambda it: -max(it[1], it[2]))
    plates = []
    for it in items:
        placed = False
        for pl in plates:
            if _try_place(pl, it):
                placed = True
                break
        if not placed:
            pl = dict(shelves=[], items=[])
            if not _try_place(pl, it):
                raise SystemExit(f"{it[0]} does not fit the bed")
            plates.append(pl)
    return plates


def _try_place(pl, it):
    name, w, d = it[0], it[1], it[2]
    for ww, dd in ((w, d), (d, w)):
        if ww > BED[0] or dd > BED[1]:
            continue
        for sh in pl["shelves"]:                       # existing shelf with room
            if dd <= sh["h"] and sh["x"] + ww <= BED[0]:
                sh["x"] += ww + GAP
                pl["items"].append(it)
                return True
        used = sum(sh["h"] + GAP for sh in pl["shelves"])
        if used + dd <= BED[1]:                        # new shelf
            pl["shelves"].append(dict(h=dd, x=ww + GAP))
            pl["items"].append(it)
            return True
    return False


def main():
    import build_all
    res = json.load(open(os.path.join(ROOT, "docs", "print_results.json")))
    parts = [(n, q) for n, _, q, _ in build_all.parts() if not n.startswith(("M0", "P1", "P2", "00_"))]
    groups = {}
    per_engine_h = per_engine_g = 0.0
    for n, q in parts:
        r = res[n]
        w, d = footprint(n)
        per_engine_h += r["hours"] * q
        per_engine_g += r["grams"] * q
        key = (r["material"], r["layer"])
        for _ in range(q * BATCH):
            groups.setdefault(key, []).append((n, w, d, r["hours"], r["grams"]))

    L = ["# 50-unit production plan", "",
         "Generated by `tools/production_plan.py` from the sliced parts (`docs/print_results.json`). "
         f"Bed {BED[0]:.0f} x {BED[1]:.0f} mm (Bambu Lab H2D / H2S class - the 260-294 mm parts need it), "
         f"all parts ASA, 0.4 mm nozzle. Small parts are pooled over a batch of {BATCH} engines.", ""]

    L += ["## 1. Printer time and filament", "",
          "| | Per engine | 50 engines (+5 % reprints) |", "|---|---|---|",
          f"| Printer-hours (sliced) | {per_engine_h:.0f} h | {per_engine_h * UNITS * REPRINT:,.0f} h |",
          f"| ASA filament | {per_engine_g / 1000:.2f} kg | {per_engine_g * UNITS * REPRINT / 1000:.0f} kg "
          f"(order {math.ceil(per_engine_g * UNITS * REPRINT / 1000 * 1.03)} x 1 kg spools, one colour batch per part family) |",
          ""]

    # where the hours and grams go
    share = sorted(((r_h * q, r_g * q, n) for n, q, r_h, r_g in
                    ((n, q, res[n]["hours"], res[n]["grams"]) for n, q in parts)), reverse=True)
    L += ["### Where the printer time goes (per engine)", "",
          "| Part | Qty | Hours | Share | Grams |", "|---|---|---|---|---|"]
    for h, g, n in share[:8]:
        q = dict(parts)[n]
        L.append(f"| {n} | {q} | {h:.1f} | {h / per_engine_h:.0%} | {g:.0f} |")
    L += ["", "Already optimised: parts nobody sees (valley beam, end plates, base panels) print at 0.28 mm; "
          "show surfaces stay at 0.20 mm and the trumpets at 0.12 mm. Deliberately NOT reduced: the base "
          "walls (4 mm) and top skin (5 mm) - a stiff, heavy base is what makes the piece feel solid and "
          "keeps the stepper's hum from turning the base into a sound box; and the 4-wall / 25 % gyroid "
          "minimum on load-bearing parts from the spec. Printing is "
          f"~${per_engine_g / 1000 * 25 + per_engine_h * 0.30:.0f} per engine (filament + machine time), "
          "under 1 % of the selling price: quality wins every one of these trade-offs.", ""]

    # plate plan for one batch
    L += [f"## 2. Plate plan for one batch of {BATCH} engines (repeat {UNITS // BATCH} times)", "",
          "| Plate | Layer | Parts on the plate | Hours |", "|---|---|---|---|"]
    total_plates = 0
    batch_h = 0.0
    for (mat, layer), items in sorted(groups.items(), key=lambda kv: -kv[0][1]):
        plates = pack(items)
        for i, pl in enumerate(plates):
            total_plates += 1
            counts = {}
            for it in pl["items"]:
                counts[it[0]] = counts.get(it[0], 0) + 1
            h = sum(it[3] for it in pl["items"])
            batch_h += h
            desc = ", ".join(f"{c} x {n}" for n, c in counts.items())
            L.append(f"| {total_plates} | {layer} mm | {desc} | {h:.1f} |")
    L += [f"| | | **{total_plates} plates per batch of {BATCH}** | **{batch_h:.0f} h** |", "",
          "Plate order inside a batch: start the long structural plates (crankcase, banks, heads, base) "
          "first so they finish while the small-part plates cycle; print the matching cosmetic parts "
          "(cam covers, side panels, end covers, exhausts, frame) from one filament lot per batch so "
          "colours match exactly.", ""]

    # farm sizing
    total_h = per_engine_h * UNITS * REPRINT
    L += ["## 3. Farm size vs calendar time", "",
          f"Total {total_h:,.0f} printer-hours at {UTILISATION:.0%} utilisation (plate changes, preheat, "
          "maintenance), printing around the clock.", "",
          "| Printers | Printing days for 50 engines | Engines per week |", "|---|---|---|"]
    for p in FARM_SIZES:
        days = total_h / (p * 24 * UTILISATION)
        L.append(f"| {p} | {days:.0f} | {UNITS / (days / 7):.1f} |")
    L += ["", "Recommended: **8 printers** - the print farm then keeps one builder busy, and the whole "
          f"order ships in about {4 + math.ceil(total_h / (8 * 24 * UTILISATION) / 7)} weeks including the "
          "first-article gate (section 5).", ""]

    # labour
    lab = sum(LABOUR_H.values())
    L += ["## 4. Labour per engine", "", "| Step | Hours |", "|---|---|"]
    L += [f"| {k.replace('_', ' ')} | {v:.2f} |" for k, v in LABOUR_H.items()]
    L += [f"| **total** | **{lab:.1f} h** (x50 = {lab * UNITS:.0f} h) |", "",
          "Part prep, board and harness building are batch work (do 5-10 at a time). Final assembly "
          "of a prepared kit is under 2 hours.", ""]

    # timeline
    p = 8
    print_days = total_h / (p * 24 * UTILISATION)
    weeks = 4 + math.ceil(print_days / 7)
    # unit #1: longest part decides once the 8 printers share the parts
    longest = max(res[n]["hours"] for n, _ in parts)
    unit1_days = max(longest, per_engine_h / p / UTILISATION) / 24
    L += ["## 5. Timeline (8 printers, 1-2 people)", "",
          "| Week | Work |", "|---|---|",
          f"| 0 | Order purchased parts for 50 + spares (BOM.md). Order machined parts M01-M06 for **2 engines** "
          f"on quick-turn and request a quote for 50. Print unit #1 (~{unit1_days + 0.5:.0f}-{unit1_days + 1.5:.0f} days on 8 printers). |",
          "| 1 | Machined parts for unit #1 arrive (quick-turn 5-10 days). Prep, build unit #1 per ASSEMBLY.md. |",
          "| 1-2 | Unit #1: 48 h burn-in, full QC record, owner review of looks and feel. |",
          "| 2 | **GATE 1 - first article approved.** Only now order the 50-unit machined batch (2-3 weeks) "
          "and start the production print run. Any change found on unit #1 goes into config.py first, "
          "everything is regenerated and re-verified, then unit #2 is built from the new files. |",
          f"| 2-{2 + math.ceil(print_days / 7)} | Production printing (~{print_days:.0f} days), batches of {BATCH}. "
          "Part prep and board building run alongside. |",
          "| 4-5 | Machined batch arrives. Assembly starts: ~2 engines per working day per builder. |",
          f"| 4-{3 + math.ceil(print_days / 7)} | Burn-in shelf of 10 turns over every 2 days; QC; packing. |",
          f"| {weeks} | Last units through burn-in, final QC, ship. |", "",
          "## 6. Risks and how they are handled", "",
          "| Risk | Mitigation |", "|---|---|",
          "| Something about the real build differs from CAD | Gate 1: one complete unit + 48 h burn-in before the batch. |",
          "| Colour mismatch between parts | One filament lot per batch of 5 for all visible parts. |",
          "| Supplier changes a part (motor cable colours, strip, ESP32 board) | Buy each purchased part for all 50 units in one order, from one batch; spares included in the BOM quantities. |",
          "| Printer fails mid-plate | +5 % reprint allowance; long plates started first; every plate checked against PRINT_REPORT.md settings. |",
          "| Machined part out of tolerance | Full first-article inspection of 5 pieces of every machined part from the batch (drawing dimensions), then 1 sample per engine kit (QC section 1); the crush-rib fits tolerate +/-0.05 on the pins anyway. |",
          "| A unit fails burn-in | Diagnose by fault code, fix, repeat the full 48 h; log every failure to spot process patterns. |", ""]
    with open(os.path.join(ROOT, "docs", "PRODUCTION_PLAN.md"), "w") as f:
        f.write("\n".join(L) + "\n")
    print("\n".join(L[:12]))
    print(f"... {total_plates} plates per batch, wrote docs/PRODUCTION_PLAN.md")


if __name__ == "__main__":
    main()
