// GENERATED by tools/gen_firmware_config.py from config.py - do not edit.
// Change config.py and re-run the generator instead.
#pragma once
#include <stdint.h>

namespace geo {
constexpr uint32_t MOTOR_FULL_STEPS = 200;
constexpr uint32_t MICROSTEPS = 16;
constexpr uint32_t DRIVE_RATIO = 3;              // 60T / 20T GT2
constexpr uint32_t STEPS_PER_REV = 9600;          // motor microsteps per crank revolution
constexpr uint32_t STEPS_PER_CYCLE = 19200;       // one 720 deg 4-stroke cycle
constexpr int N_CYL = 10;
constexpr int FIRING_ORDER[N_CYL] = {1, 6, 5, 10, 2, 7, 3, 8, 4, 9};
// step (within the 720 deg cycle, counted from cylinder 1 firing TDC) at which
// each cylinder fires; index 0 = cylinder 1
constexpr uint32_t FIRE_STEP[N_CYL] = {0, 7680, 11520, 15360, 3840, 1920, 9600, 13440, 17280, 5760};

constexpr int LEDS_PER_STRIP = 15;
constexpr int LEDS_PER_CYL = 3;
// strip LED k (k = 0 at the rear, data-in end): cylinder number and position
// in its group (0 = rear LED, 1 = centre of the bore, 2 = front LED)
constexpr uint8_t LED_CYL_A[LEDS_PER_STRIP] = {5, 5, 5, 4, 4, 4, 3, 3, 3, 2, 2, 2, 1, 1, 1};
constexpr uint8_t LED_POS_A[LEDS_PER_STRIP] = {0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2};
constexpr uint8_t LED_CYL_B[LEDS_PER_STRIP] = {10, 10, 10, 9, 9, 9, 8, 8, 8, 7, 7, 7, 6, 6, 6};
constexpr uint8_t LED_POS_B[LEDS_PER_STRIP] = {0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2};

constexpr float RPM_MIN = 20.0f;
constexpr float RPM_MAX = 120.0f;
constexpr float RPM_IDLE = 20.0f;
constexpr float RPM_HOMING = 15.0f;
constexpr float ACCEL_RPM_S = 15.0f;
constexpr uint32_t AUTO_IDLE_MIN = 5;
constexpr uint32_t AUTO_SLEEP_MIN = 15;
constexpr uint16_t MOTOR_RUN_MA = 600;
constexpr float MOTOR_HOLD_FRACTION = 0.35f;
// the hall magnet passes the sensor this many steps after cylinder 1 firing TDC
// (crank angle 216.0 deg: magnet in the rear end web)
constexpr uint32_t HALL_PHASE_STEPS = 5760;
constexpr uint32_t HALL_MIN_WIDTH = 53;      // steps
constexpr uint32_t HALL_MAX_WIDTH = 2400;
constexpr int32_t SYNC_CORRECT_STEPS = 80;
constexpr int32_t SYNC_FAULT_STEPS = 213;
constexpr uint32_t NO_HALL_STEPS = 13440;
constexpr uint32_t FLASH_STEPS = 2933;
constexpr uint8_t LED_MAX_BRIGHTNESS = 170;
}  // namespace geo
